version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: alphaCampDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  springbootapp:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: springbootapp
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data_volume:
    driver: local
  jenkins_home: